INSERT INTO Anime (AnimeID, TitleEnglish, TitleRomaji, TitleNative, Genre, ReleaseDate, EndDate, AnimeStatus, Synopsis, PopularityPosition, CoverImageURL, BackgroundImageURL, StreamingPlatformURL, Format, EpisodeCount, EpisodeDuration)
VALUES
(1,'Naruto', 'NARUTO', 'ナルト', 'Action, Adventure, Fantasy, Comedy, Martial arts, Supernatural, Drama', '2002-10-03', '2007-02-08', 'Finished', 'Naruto Uzumaki, a spirited and energetic ninja, resides in Konohagakure, the Hidden Leaf village. His birth coincided with a catastrophic attack by the Kyuubi, a colossal Nine-tailed Fox, which led to the Fourth Hokage’s self-sacrifice to seal the formidable beast within the newborn Naruto.\n\nIsolated by the villagers due to the Kyuubi’s presence within him, Naruto grapples with finding his identity in the community. His relentless ambition is to ascend to the role of Hokage in Konohagakure, a journey marked by encounters with both allies and adversaries.',NULL, 'https://i.imgur.com/6xMgscD.jpg', 'https://i.imgur.com/KF0mp16.png', 'https://9animetv.to/watch/naruto-677?ep=12352', 'TV', 220, 23),


(2,'One Piece', 'One Piece', 'ワンピース', 'Action, Adventure, Comedy, Fantasy', '1999-10-20', NULL, 'Ongoing', 'Gold Roger, the legendary Pirate King, once reigned as the mightiest and most infamous figure to ever navigate the treacherous waters of the Grand Line. His capture and eventual execution at the hands of the World Government sent shockwaves throughout the world, and his parting words disclosed the coveted secret of the world’s greatest treasure, One Piece.\n\nOne Piece follows Monkey D. Luffy, who gains rubber-like powers and sets out to become the Pirate King. With his crew, the Straw Hat Pirates, they explore a vast world, encounter extraordinary characters, and pursue the legendary treasure known as "One Piece." Their journey is filled with adventure, battles, and the pursuit of dreams in a colorful and action-packed world.', NULL, 'https://i.imgur.com/040ScO4.jpg', 'https://i.imgur.com/fq6VC5R.jpg', 'https://www.crunchyroll.com/fr/series/GRMG8ZQZR/one-piece', 'TV', 1078,24),


(3,'Death Note', 'Death Note', 'デスノート', 'Mystery, Psychological, Thriller, Mystery, Supernatural', '2006-10-04', '2007-06-27', 'Finished', 'Death Note follows the story of Light Yagami, a highly intelligent high school student who stumbles upon a mysterious notebook known as the Death Note. The Death Note has the power to kill anyone whose name is written in it, provided the writer knows the person’s face. Driven by a strong sense of justice, Light begins using the Death Note to eliminate criminals and create a utopian world free of wrongdoing.\n\nHowever, Light’s actions do not go unnoticed. A brilliant and enigmatic detective known only as "L" is determined to apprehend the elusive killer, sparking a high-stakes game of cat and mouse between the two masterminds. As Light and L engage in a battle of wits, the Death Note’s power and the consequences of Light’s actions lead to a series of moral and philosophical dilemmas. The series delves into themes of justice, morality, and the consequences of absolute power in a thrilling and thought-provoking manner.', NULL, 'https://i.imgur.com/Y0P53pc.jpg', 'https://i.imgur.com/HC69SoJ.png', 'https://9animetv.to/watch/death-note-60?ep=1464', 'TV', 37,23),

(4,'Attack on Titan', 'Shingeki no Kyojin', '進撃の巨人', 'Action, Fantasy, Horror, Post-apocalyptic, Mystery, Drama, Dark Fantasy', '2013-04-07', '2013-09-28', 'Finished', 'In a world where humanity is on the brink of extinction due to giant humanoid creatures known as Titans, Attack on Titan follows the story of Eren Yeager and his friends Mikasa and Armin. After witnessing the destruction of their walled city and the death of Eren’s mother at the hands of Titans, they join the Scout Regiment to fight back.\n\nAs they uncover the mysteries surrounding the Titans and the walls that protect them, the series explores themes of survival, freedom, and the consequences of discovering long-buried truths.', NULL, 'https://i.imgur.com/XGOw9dK.png', 'https://i.imgur.com/TQiAnX9.jpg', 'https://9animetv.to/watch/attack-on-titan-112?ep=3303', 'TV', 25, 24),

(5,'My Hero Academia', 'Boku no Hero Academia', '僕のヒーローアカデミア', 'Action, Superpower, Shounen, Adventure, Comedy', '2016-04-03', '2016-06-26', 'Ongoing', 'In a world where people with superpowers, known as Quirks, are common, My Hero Academia centers on Izuku Midoriya, a Quirkless boy with dreams of becoming a hero. His life takes a remarkable turn when he inherits the Quirk of the world’s greatest hero, All Might.\n\nEnrolling in U.A. High School, he trains alongside other aspiring heroes, including his rival Katsuki Bakugo and his idol, All Might. The series explores themes of heroism, the struggle for self-discovery, and the challenges of living up to one’s ideals in a society filled with heroes and villains.', NULL, 'https://i.imgur.com/VBvo4fy.png', 'https://i.imgur.com/zAeODYu.png', 'https://www.crunchyroll.com/fr/series/G6NQ5DWZ6/my-hero-academia', 'TV', 13,24),

(6,'Demon Slayer', 'Kimetsu no Yaiba', '鬼滅の刃', 'Action, Historical, Supernatural, Fantasy, Drama, Supernatural, Martial arts, Dark Fantasy', '2019-04-06', '2019-09-28', 'Finished', 'Set in the Taisho-era Japan, "Demon Slayer" introduces us to Tanjiro Kamado, a compassionate young boy. His life takes a dark turn when his family is brutally slaughtered by demons, and his sister, Nezuko, is transformed into one of these creatures. Driven by a deep desire for vengeance and to find a cure for Nezuko, Tanjiro becomes a demon slayer.\n\nAs he ventures into a perilous world filled with demons and demon slayers, Tanjiro discovers the intricacies of demon lore, battles formidable foes, and unveils the mysteries of his world. His journey is a quest for justice, redemption, and ultimately, a way to restore his sister.', NULL, 'https://i.imgur.com/vdf6mmq.jpg', 'https://i.imgur.com/zn4q3Ai.png', 'https://www.crunchyroll.com/fr/series/GY5P48XEY/demon-slayer-kimetsu-no-yaiba', 'TV', 26,24),

(7,'One Punch Man', 'One Punch Man', 'ワンパンマン', 'Action, Comedy, Superpower, Fantasy, Adventure, Drama', '2015-10-05', '2015-12-21', 'Finished', 'In a world where monsters and villains threaten humanity, Saitama, an unassuming hero with unmatched strength, finds himself in an unusual predicament: he can defeat any adversary with a single punch. Despite his god-like powers, Saitama becomes disillusioned by the lack of challenge in his fights. He longs for an opponent who can truly test his abilities and ignite his passion for heroism.\n\nIn the midst of this, he navigates the complexities of hero association rankings, faces absurdly powerful foes, and wrestles with existential questions about purpose and recognition.', NULL, 'https://i.imgur.com/4G6h4Xf.jpg', 'https://i.imgur.com/VTLqZIF.png', 'https://www.crunchyroll.com/fr/series/G63K98PZ6/one-punch-man', 'TV', 12,24),

(8,'Sword Art Online', 'Sword Art Online', 'ソードアート・オンライン', 'Action, Adventure, Fantasy, Romance', '2012-07-08', '2012-12-23', 'Finished', 'In the near future, players of the groundbreaking virtual reality MMORPG "Sword Art Online" are trapped within the game’s digital world. Kirito, one of the players, embarks on a treacherous journey to clear the game’s levels and free himself and others from this virtual prison.\n\nAlong the way, he forges deep connections with other players, falls in love, and confronts the stark realities of life and death within the game. Kirito’s quest is not only about survival but also about discovering the boundaries between reality and the digital realm.', NULL, 'https://i.imgur.com/j6ezYZF.jpg', 'https://i.imgur.com/xUIL5pK.jpg', 'https://www.crunchyroll.com/fr/series/GR49G9VP6/sword-art-online', 'TV', 25,23),

(9,'Naruto Shippuden', 'NARUTO -ナルト- 疾風伝', 'ナルト 疾風伝', 'Action, Adventure, Fantasy, Comedy, Martial arts, Supernatural, Drama', '2007-02-15', '2017-03-23', 'Finished', '"Naruto Shippuden" is the continuation of the epic saga of Naruto Uzumaki, the spirited young ninja. As Naruto matures, he faces ever greater challenges in his journey towards becoming Hokage. One of his most compelling quests is his unwavering determination to bring back his friend Sasuke Uchiha, who has gone rogue in search of power.\n\nIn the wake of Sasuke’s departure, a new threat emerges in the form of the Akatsuki, a secretive organization of formidable rogue ninjas. These dangerous individuals possess supernatural abilities and are on a mission to capture the Tailed Beasts, powerful demon creatures, to further their nefarious plans. As the Akatsuki’s actions send shockwaves throughout the ninja world, Naruto and his allies must not only confront this menacing group but also protect the Tailed Beasts from falling into the wrong hands.\n\nThe series delves deep into themes of identity, destiny, and sacrifice, as Naruto, his friends, and even former enemies grow and evolve. Naruto’s journey becomes a complex tapestry of battles against external foes, such as the Akatsuki, while also delving into the profound inner struggles and growth of the characters. With every challenge and every encounter, "Naruto Shippuden" explores the intertwined destinies of its characters and the intricate web of loyalties and rivalries that define the ninja world.', NULL, 'https://i.imgur.com/TbWpmAy.jpg', 'https://i.imgur.com/O0ypA40.jpg', 'https://www.crunchyroll.com/fr/series/GYQ4MW246/naruto-shippuden', 'TV', 500,23),

(10,'Akame ga Kill!', 'Akame ga Kiru!', 'アカメが斬る！', 'Action, Adventure, Fantasy, Dark Fantasy, Drama, Horror, Psychological, Thriller', '2014-07-07', '2014-12-15', 'Finished', 'In a world plagued by corruption, where a ruthless Prime Minister wields the puppet Emperor’s armies, assassins, and secret police against the people, a courageous force emerges to challenge this oppressive regime: Night Raid. This elite team comprises relentless killers, each armed with an Imperial Arm, legendary weapons of immense power created in the distant past.\n\nYoung Tatsumi, rescued from a dire fate by Night Raid, faces a fateful decision. He’s offered the opportunity to join their lethal ranks, but the path he treads is treacherous. Few can master the might of an Imperial Arm, and even fewer survive when these legendary weapons clash in combat. The battle is set, and only the strongest will emerge from the crucible alive. "Akame ga Kill" is a tale of defiance, power, and the unforgiving choices made in the pursuit of justice in a world teetering on the brink of despair.', NULL, 'https://i.imgur.com/pOcF4xC.jpg', 'https://i.imgur.com/8MXnRbH.jpg', 'https://9animetv.to/watch/akame-ga-kill-1329?ep=19306', 'TV', 24,24),

(11,'Code Geass: Lelouch of the Rebellion', 'Kōdo Giasu: Hangyaku no Rurūshu', 'コードギアス 反逆のルルーシュ', 'Action, Mecha, Drama, Supernatural, Drama, Sci-Fi, Thriller', '2006-10-06', '2007-07-28', 'Finished', 'In an alternate world where the Holy Britannian Empire dominates Japan, Lelouch vi Britannia, a dispossessed prince, gains a supernatural power known as Geass. With the ability to command anyone to obey his will, Lelouch embarks on a mission to destroy the empire that wronged him and create a better world for his sister.\n\nHis journey is a complex exploration of power, morality, and the consequences of his actions as he becomes a masked revolutionary known as Zero. The series offers political intrigue, strategic warfare, and a compelling narrative that delves into the complexities of leadership and revolution.', 2, 'https://i.imgur.com/vlXP6r1.png', 'https://i.imgur.com/QHPQsum.jpg', 'https://9animetv.to/watch/code-geass-lelouch-of-the-rebellion-41?ep=1158', 'TV', 25,24);

