-- naruto
INSERT INTO Character_Card (CharacterID, CharName, Birthday, Age, Gender, BloodType, Height, CharDescription, ImageURL, isMainCharacter, Likes, Family, CharNamesGiven, HiddenSurCharNames)
VALUES
(1,'Naruto Uzumaki', 'Oct 10', '12-13 (Naruto), 15-17 (Naruto Shippuden), 27- (Boruto)', 'Male', 'B', '145-180 cm', 'Naruto Uzumaki is the heart of the series and its main protagonist. He’s a spirited and energetic ninja with a dream of becoming the Hokage of Konohagakure, the Hidden Leaf Village. Naruto was born with the Nine-Tails, a powerful demon fox, sealed inside him. This unfortunate circumstance led to his isolation and rejection by the villagers. Naruto’s character is marked by unwavering determination and a desire to prove his worth to the people who shunned him. As the story unfolds, Naruto’s journey is one of growth, friendship, and the pursuit of his dreams.', 'https://i.imgur.com/dG3jIEC.png', 1, 0, 'Minato Namikaze (Father), Kushina Uzumaki (Mother), Boruto Uzumaki (Son), Hinata Hyuga (Wife), Himawari Uzumaki (Daughter), Jiraiya (Godfather)', 'うずまきナルト Uzumaki Naruto, The Show-Off, Number One Unpredictable, Noisy Ninja, Hyperactive, Knucklehead Ninja', 'Child of the Prophecy, Saviour of this World, Hero of the Hidden Leaf, Boy of Miracles, Konoha’s Orange Hokage, Seventh Hokage, Nanadaime Hokage'),

(2,'Sasuke Uchiha', 'July 23', '12-13 (Naruto), 16-17 (Naruto Shippuden)', 'Male','AB', '150.8-182 cm', 'Sasuke Uchiha is a complex character in the Naruto series. He is known as one of the last surviving members of the Uchiha clan, which was annihilated by his older brother, Itachi. Consumed by a thirst for power and a desire for vengeance against Itachi, Sasuke leaves the Hidden Leaf Village in pursuit of strength and darker ambitions. He is driven by the need to prove himself and avenge his clan’s massacre. His journey takes him down a path of darkness, and his complex character development explores themes of redemption and sacrifice.', 'https://i.imgur.com/pJbct07.png', 0, 0, NULL, 'うちはサスケ, Sasuke of the Sharingan','Child of the Prophecy, Supporting Kage'),

(3,'Sakura Haruno', 'March 28', '12-13 (Naruto), 15-17 (Naruto Shippuden)', 'Female','O', '148.5-165 cm', 'Sakura Haruno is a member of Team 7, alongside Naruto and Sasuke. At the start of the series, she’s portrayed as timid and often overshadowed by her teammates. However, Sakura’s character development leads her to grow into a formidable ninja with exceptional medical skills. Her determination to protect her friends and become a stronger ninja is a central theme in her character arc.', 'https://i.imgur.com/yZTBJcr.png', 0, 0, NULL, '春野サクラ, Forehead Girl','Sakura Uchiha, Tsunade Number Two'),

(4,'Kakashi Hatake', 'Sep 15', '26-27 (Naruto), 29-31 (Naruto Shippuden)', 'Male','O', '181 cm', 'Kakashi Hatake is the skilled and enigmatic sensei of Team 7. He is known for his mysterious demeanor and for having the Sharingan eye. Kakashi imparts crucial knowledge and guidance to Naruto, Sasuke, and Sakura as they embark on their ninja journey. His character is marked by a deep sense of duty and the responsibility of shaping the next generation of ninjas.', 'https://i.imgur.com/JQJhUZM.png', 0, 0, NULL, 'はたけカカシ, Copy Ninja Kakashi, Kakashi of the Sharingan, Cold-Blooded Kakashi, Sukea', 'Sixth Hokage, Konoha’s First Technician, Hero of the Sharingan, Friend-Killer Kakashi'),

(5,'Jiraiya', 'Nov 11', '50-51 (Naruto), 54 (Naruto Shippuden)', 'Male','B', '191 cm cm', 'Jiraiya, one of the legendary Sannin, is a renowned ninja and a mentor to Naruto. He is known for his perverted tendencies and flamboyant personality but is also a wise and skilled sage. Jiraiya plays a pivotal role in Naruto’s training and development, teaching him vital ninja techniques and life lessons.', 'https://i.imgur.com/IDTP9Ih.jpg', 0, 0, NULL, '自来也, Toad Sage, The Village’s Madness, Perverted Hermit', NULL),

(6,'Itachi Uchiha', 'June 9', '17-18 (Naruto), 21 (Naruto Shippuden)', 'Male', 'AB', '175-178 cm', 'Itachi Uchiha is Sasuke’s enigmatic and powerful older brother. He is a complex character with a mysterious past. Itachi’s actions, including the extermination of their clan, have a profound impact on Sasuke’s life and the broader storyline. The character of Itachi is shrouded in secrets, and his true motivations are slowly revealed throughout the series.', 'https://i.imgur.com/a3Yjk2K.png', 0, 0, NULL, 'うちはイタチ, Itachi of the Sharingan, Clan Killer Itachi', NULL),

(7,'Gaara', 'January 19', '12-13 (Naruto), 15-17 (Naruto Shippuden)', 'Male', 'AB', '146-172 cm', 'Gaara is initially introduced as a fearsome antagonist but undergoes significant character development. He hails from the Hidden Sand Village and carries a tragic past marked by isolation and violence. Through his journey, Gaara learns the value of friendship and bonds with Naruto and others, eventually becoming the Kazekage and a protector of his village.', 'https://i.imgur.com/SZi8cLx.png', 0, 0, NULL, '我愛羅, Gaara of the Sand, Gaara of the Sand Waterfall', 'Fifth Kazekage, The Golden Child, Prince of the Sand Waterfall Gourd');


-- One piece
INSERT INTO Character_Card (CharacterID, CharName, Birthday, Age, Gender, BloodType, Height, CharDescription, ImageURL, isMainCharacter, Likes, Family, CharNamesGiven, HiddenSurCharNames)
VALUES
(8,'Monkey D. Luffy', 'May 5', '7 (debut), 17 (pre-timeskip), 19 (after timeskip)', 'Male', 'F', '172-174 cm', 'Captain of the Straw Hat Pirates.', 'https://i.imgur.com/wQN3Izp.jpg', 1, 0, NULL, 'モンキー・D・ルフィ, Straw Hat, Mugiwara, Straw, Mugi, Lucy, Luffyland, Luffy-tarou, Mugiwara no Luffy, Mugiwara-ya', 'The Fifth Emperor of the Sea, Sun God Nika, Joy Boy');

-- death note
INSERT INTO Character_Card (CharacterID, CharName, Birthday, Age, Gender, BloodType, Height, CharDescription, ImageURL, isMainCharacter, Likes, Family, CharNamesGiven, HiddenSurCharNames)
VALUES
(9,'Light Yagami', 'Feb 28', '17-23', 'Male', 'A', '179 cm', 'Protagonist and owner of the Death Note.', 'https://i.imgur.com/tpGUOhO.jpg', 1, 0, NULL, '夜神月, Kira, Light Asahi, God', '(Second) L, L-Kira'),

(10,'L', 'Oct 31', '24-25', 'Male', 'Unknown', '179 cm', 'The brilliant and enigmatic detective trying to catch Kira.', 'https://i.imgur.com/fGX0b0D.jpg', 0, 0, NULL, 'エル・ローライト, Ryuzaki, Eraldo Coil, Suzuki, Asahi, L-Prime, Ryuga Hideki, Deneuve', NULL);

-- Attack on titan
INSERT INTO Character_Card (CharacterID, CharName, Birthday, Age, Gender, BloodType, Height, CharDescription, ImageURL, isMainCharacter, Likes, Family, CharNamesGiven, HiddenSurCharNames)
VALUES
(11,'Eren Yeager', 'Mar 30', '15-17', 'Male', NULL, '170-183 cm', 'Eren Yeager is a pivotal character in "Attack on Titan." At the series’ outset, he is a young and determined member of the Scout Regiment. Eren is driven by an unwavering desire for freedom and the opportunity to explore the world beyond the Walls that confine humanity. His character evolves significantly as the story progresses. Eren’s journey is marked by the discovery of the power of the Attack Titan, his transformation into a Titan Shifter, and his mission to uncover the truths hidden within the Walls.\n\nEren’s character is defined by his complex emotions, which range from rage against the Titans to a longing for freedom. His fearless pursuit of freedom sometimes leads him to make difficult choices, and his transformation from a boy full of dreams to a formidable leader is central to the series. Eren’s character arc explores themes of vengeance, sacrifice, and the consequences of one’s actions in a world filled with existential threats.', 'https://i.imgur.com/gPRz5BR.jpg', 1, 0, NULL, 'エレン・イェーガー, Suicidal Blockhead, Eren Jaeger, Eren Jäger', 'Attack Titan, Mister Kruger, Founding Titan, Founder, Usurper, War Hammer Titan, Doomsday Titan'),

(12,'Mikasa Ackerman', 'Feb 10', '15-19', 'Female', 'B', '170-176 cm', 'Mikasa Ackerman is Eren’s adoptive sister and one of the most skilled fighters within the Scout Regiment. She is fiercely protective of Eren and displays incredible combat abilities. Despite her stoic and reserved demeanor, Mikasa’s character is deeply rooted in her love for Eren and the desire to keep him safe. Her loyalty to Eren is unwavering, and her determination to shield him from harm is a central theme in her character development.\n\nMikasa’s character arc delves into themes of identity, strength, and the enduring bonds of family. Her backstory, including the trauma she experienced as a child, adds depth to her character. Throughout the series, Mikasa grapples with her emotions, her place in the world, and her commitment to the cause of defeating the Titans. She is a symbol of resilience and determination, serving as both a protector and a symbol of hope within the story.', 'https://i.imgur.com/thaIM3H.png', 0, 0, NULL, 'ミカサ・アッカーマン', NULL);

-- My hero academia
INSERT INTO Character_Card (CharacterID, CharName, Birthday, Age, Gender, BloodType, Height, CharDescription, ImageURL, isMainCharacter, Likes, Family, CharNamesGiven, HiddenSurCharNames,SpecificField1)
VALUES

(13,'Izuku Midoriya', 'July 15', '14-16', 'Male', 'O', '166 cm', 'Izuku Midoriya, often referred to as Deku, is the series’ main protagonist. Born without a Quirk in a world where superpowers are common, Izuku’s journey is one of inspiration. He inherits the Quirk of All Might, the world’s greatest hero, and attends U.A. High School to pursue his dream of becoming a hero. His character embodies themes of determination, courage, and the pursuit of one’s goals despite seemingly insurmountable odds.', 'https://i.imgur.com/0q8RP7H.png', 1, 0, NULL, '緑谷出久, Deku', NULL, '<b>Quirk:</b> One For All'),

(14,'Katsuki Bakugo', 'April 20', '14-17', 'Male', 'A', '172 cm', 'Katsuki Bakugo, also known as Kacchan, is one of Izuku Midoriya’s childhood friends and rivals. He possesses a powerful explosion-based Quirk and has a brash and aggressive personality. Bakugo’s character is marked by his fierce determination to become the number one hero, which sometimes leads to conflicts with others. His development explores themes of pride, growth, and understanding the true meaning of heroism.', 'https://i.imgur.com/2RWjjhp.png', 0, 0, NULL, 'Kacchan, Great Explosion Murder God Dynamight', NULL, '<b>Quirk:</b> Explosion'),

(15,'Shoto Todoroki', 'Jan 11', '15-16', 'Male', 'O', '176 cm', 'Shoto Todoroki is a prominent character in "My Hero Academia." He is a student at U.A. High School and possesses a Quirk that combines both fire and ice abilities, inherited from his hero parents. Shoto initially struggles with his past and the expectations of his father, Endeavor, but overcomes these challenges to become a powerful hero. His character arc delves into themes of identity, reconciliation, and using one’s powers for the greater good.', 'https://i.imgur.com/yOZwMH4.png', 0, 0, NULL, '轟焦凍, Shoto Todoroki, Half-and-Half, Icy-Hot', NULL,'<b>Quirk:</b> Half-Cold Half-Hot');

-- Demon slayer
INSERT INTO Character_Card (CharacterID, CharName, Birthday, Age, Gender, BloodType, Height, CharDescription, ImageURL, isMainCharacter, Likes, Family, CharNamesGiven, HiddenSurCharNames, SpecificField1)
VALUES
(16,'Tanjiro Kamado', 'Jul 14', '13-16', 'Male', 'A', '165 cm', 'Tanjiro Kamado is the heart and soul of "Demon Slayer." He is a kind-hearted and determined young boy who becomes a demon slayer after his family is brutally slaughtered by demons, with his sister Nezuko turned into one. Tanjiro’s character is defined by his unwavering commitment to protecting humanity from demons and finding a cure for his sister. His journey is one of growth, courage, and empathy as he confronts the harsh realities of the demon-slaying world.', 'https://i.imgur.com/jnih637.jpg', 1, 0, NULL, '竈門炭治郎, Gonpachiro Kamaboko, Monjiro, Santaro, Kentaro, Soichiro, Ponjiro, Gengo Shakariki, Tontaro Itadaki, Kanjiro Anago, Tangoro Hamado, Jangoro Amado', 'King Of Demons','<b>Combat Style:</b> Water Breathing and Sun Breathing'),

(17,'Nezuko Kamado', 'Dec 28', '12-14', 'Female', 'A', '153 cm', 'Nezuko Kamado is Tanjiro’s younger sister who, tragically, is turned into a demon. Despite this transformation, Nezuko retains her protective instincts and deep love for her brother. She doesn’t succumb to her demonic nature and strives to assist Tanjiro in his quest. Nezuko’s character is marked by her resilience and the unique abilities she gains as a demon.', 'https://i.imgur.com/c6Naogo.jpg', 0, 0, NULL, '竈門禰豆子, 竈門禰?豆子', 'The Chosen Demon (選ばれし鬼), Erabareshi Oni', NULL),

(18,'Giyuu Tomioka', 'Feb 8', '19-21', 'Male', NULL, '176 cm', 'A Water Hashira and skilled demon slayer.', 'https://i.imgur.com/eNxvqKl.jpg', 0, 0, NULL, '冨岡義勇, Water Hashira, Water Pillar, Half-and-half Haori', NULL,'<b>Combat Style:</b> Water Breathing'),

(29,'Kyojuro Rengoku', 'May 10', '20', 'Male', NULL, '177 cm', 'Kyojuro Rengoku, the Flame Hashira in "Demon Slayer," is a charismatic and highly skilled member of the Demon Slayer Corps. He’s recognized by his fiery personality, powerful flame-breathing techniques, and vibrant sense of duty. Kyojuro is a symbol of hope, known for his unwavering commitment to protecting humanity from demons and his ability to inspire others with his optimism and determination. His character shines through both on and off the battlefield, making him a beloved and memorable figure in the series.', 'https://i.imgur.com/28tbu62.png', 0, 0, NULL, '煉獄杏寿郎, Flame Hashira, Flame Pillar, Ildsøylen, Googly Eyes', NULL,'<b>Combat Style:</b> Flame Breathing'),

(19,'Akaza', 'Unknown', '18 (human), 133+ (demon)', 'Male', 'Unknown', '173 cm', 'A powerful demon who battles the demon slayers.', 'https://i.imgur.com/f6ueGBc.jpg', 0, 0, NULL, '猗窩座, Hakuji, Upper Moon Three', NULL, NULL);

-- one punch man
INSERT INTO Character_Card (CharacterID, CharName, Birthday, Age, Gender, BloodType, Height, CharDescription, ImageURL, isMainCharacter, Likes, Family, CharNamesGiven, HiddenSurCharNames)
VALUES
(20,'Saitama', 'Apr 21', '25-', 'Male', NULL, '175 cm', 'An overpowered hero who can defeat any opponent with a single punch.', 'https://i.imgur.com/dPvX2vh.jpg', 1, 0, NULL, 'サイタマ, One Punch Man, Bald Cape, ハゲマント, Hagemanto, Caped Baldy', 'The Fist That Has Turned Against God (神に仇なす拳), Kami ni Adanasu-Ken, Fists That Wrong The Gods'),

(21,'Genos', NULL , '19-', 'Male', 'Unknown', '178 cm', 'Cyborg hero and disciple of Saitama seeking revenge.', 'https://i.imgur.com/QORo8Kc.jpg', 0, 0, NULL, 'ジェノス, Demon Cyborg', NULL);

-- sword art online
INSERT INTO Character_Card (CharacterID, CharName, Birthday, Age, Gender, BloodType, Height, CharDescription, ImageURL, isMainCharacter, Likes, Family, CharNamesGiven, HiddenSurCharNames,SpecificField1)
VALUES
(22,'Kazuto Kirigaya', 'Oct 7', '14-18', 'Male', NULL, '172 cm', 'Skilled solo player in the virtual world of SAO.', 'https://i.imgur.com/vgSvOqz.jpg', 1, 0, NULL, '桐ヶ谷和人, Kirito (キリト), The Black Swordsman, Beater, Daddy (パパ)', 'Kazuto Narusaka', '<b>Weapons:</b> Anneal Blade (1st Level), Queen’s Knightblade (9th Level), Elucidator (50th level) and Dark Repulser (forged by Lisbeth)'),

(23,'Asuna Yuuki', 'Sep 30', '15-19', 'Female', 'Unknown', '167 cm', 'Swordswoman and Kirito’s love interest in SAO.', 'https://i.imgur.com/vgSvOqz.jpg', 0, 0, NULL, '結城明日奈, アスナ, Titania (ティターニア), Berserker Healer (バーサクヒーラー), Lightning Flash (閃光), Mommy (ママ), Erika (エリカ)', 'Stacia (ステイシア), Suteishia','<b>Weapons:</b> Wind Fleuret (1st Floor), Lambent Light (Forged by Lisbeth)');

-- akame ga kill
INSERT INTO Character_Card (CharacterID, CharName, Birthday, Age, Gender, BloodType, Height, CharDescription, ImageURL, isMainCharacter, Likes, Family, CharNamesGiven, HiddenSurCharNames, SpecificField1)
VALUES
(24, 'Tatsumi', 'Feb 29', 'Teens', 'Male', 'O', '165 cm', 'A young fighter who joins Night Raid to fight corruption.', 'https://i.imgur.com/xVC4Ayc.jpg', 1, 0, NULL, 'タツミ, Tatsumi The Blacksmith', NULL,'<b>Teigu:</b> Incursio'),
(25, 'Akame', NULL, '18-20 (Akame ga Kill)', 'Female', 'A', '164 cm', 'A skilled assassin in Night Raid with deadly Teigu.', 'https://i.imgur.com/mpBcQ07.jpg', 1, 0, NULL, 'アカメ, Akame of the Demon Sword Murasame', NULL,'<b>Teigu:</b> Murasame');


-- code geass
INSERT INTO Character_Card (CharacterID, CharName, Birthday, Age, Gender, BloodType, Height, CharDescription, ImageURL, isMainCharacter, Likes, Family, CharNamesGiven, HiddenSurCharNames, SpecificField1)
VALUES
(26,'Lelouch Lamperouge', 'Dec 5,2000', '17-18', 'Male', 'A', '178 cm', 'Lelouch Lamperouge, also known by his alter ego Lelouch vi Britannia, is a central character in the anime series "Code Geass: Lelouch of the Rebellion." He is a complex and enigmatic figure, known for his intelligence, charisma, and his relentless pursuit of justice.\n\nLelouch is a young man with dark hair and violet eyes. He possesses a brilliant tactical mind and a charismatic presence that makes him a natural leader. He’s a former prince of the Holy Britannian Empire, a powerful and oppressive nation that has conquered Japan and reCharNamed it Area 11. Despite his royal lineage, Lelouch harbors a deep-seated hatred for the Britannian Empire due to personal reasons.\n\nAfter acquiring the power of Geass from a mysterious girl CharNamed C.C., Lelouch gains the ability to command anyone to do his bidding, provided he makes direct eye contact with them. With this newfound power, he dons the identity of "Zero" and becomes the masked leader of the rebel group known as the Black Knights. Lelouch’s ultimate goal is to bring down the Britannian Empire, seeking justice for himself, his sister Nunnally, and all oppressed people.\n\nLelouch is a morally complex character who is willing to employ ruthless tactics and make difficult decisions to achieve his objectives. His character development and interactions with other key figures in the series contribute to the depth and intrigue of "Code Geass." Lelouch Lamperouge’s journey is one of rebellion, sacrifice, and the pursuit of a better world, making him a memorable and compelling character in the world of anime.', 'https://i.imgur.com/BbmRErr.jpg', 1, 0, 'Charles zi Britannia (father), Marianne vi Britannia (mother, deceased), Nunnally vi Britannia (little sister), Rolo Lamperouge (Foster Brother), Clara Lamperouge (Temporary Foster Sister)', 'ルルーシュ・ランペルージ, Lulu, Lelouch vi Britannia, Black Prince, Zero, King of Elevens, The Demon, Black King, Black Demon, Julius Kingsley', '99th Emperor of Britania, L.L.','<b>Nationality:</b> Britannian\n\n<b>Allegiance:</b> Order of the Black Knights'),

(27, 'C.C.', 'Mar 21', ' 16 (biologically), Around 300', 'Female', 'Unknown', '168 cm', 'C.C., whose true CharName is concealed, is a mysterious and enigmatic character in the anime series "Code Geass: Lelouch of the Rebellion." She possesses a unique and powerful ability known as a Geass, similar to the protagonist Lelouch Lamperouge. C.C. plays a central role in the series as both an ally and a source of intrigue.\n\nC.C. is known for her calm and detached demeanor, often characterized by her love for pizza and her enigmatic smile. She becomes linked to Lelouch after granting him his Geass power, and their complex and evolving relationship is a key aspect of the storyline.\n\nThroughout the series, C.C.’s character is shrouded in mystery, and her origins and motivations remain a subject of intrigue. Her presence adds an element of mystique and fantasy to the world of "Code Geass." C.C. is a character with hidden depths and an integral part of the anime’s intricate plot.\n\nAs the story unfolds, viewers will come to appreciate C.C.’s character for her unique qualities and her role in shaping the destiny of the series’ protagonist.', 'https://i.imgur.com/69LbaRu.png', 0, 0, NULL, 'シー･ツー, Witch of Britannia, Gray Witch, Pizza Girl, C2', NULL,'<b>Allegiance:</b> The Black Knights'),

(28,' Suzaku Kururugi', 'July 10,2000', '17-18 (Code Geass)', 'Male', 'O', '176 cm', 'Suzaku, Lelouch’s childhood friend and the son of Japan’s last prime minister, undergoes a significant transformation in the wake of Britannia’s conquest of Japan. He chooses to enlist in the Britannia Army and gains the status of an Honorary Britannian. While Suzaku shares Zero’s (Lelouch’s alter ego, unbeknownst to him) belief that the Britannia Empire is not a just cause, he’s determined to bring about change and improvements from within the empire. His unwavering commitment to this mission is driven by a desire to honor his father’s legacy.\n\Suzaku possesses a strong sense of justice and becomes the exclusive pilot of the elite Britannian Knightmare Frame, known as Lancelot. He cherishes a broken pocket watch, a poignant keepsake from his late father, which serves as a constant reminder of his underlying motivation. Suzaku’s journey in the series revolves around the complex interplay of duty, justice, and personal convictions.', 'https://i.imgur.com/v9yxi6g.jpg', 0, 0, 'Genbu Kururugi (father, deceased), Kaguya Sumeragi (cousin)', '枢木スザク, White Knight, White Grim Reaper, Knight of Seven, Spinzaku', 'Knight of Zero, Zero','<b>Nationality:</b> Japanese');

-- 29 =  kyojurou rengoku